external_url: "https://corp-ppr.gitlab.vnet.valeo.com"
gitlab_aws_rds_endpoint: "dul9-sv03091.ctbwzaho8rdv.eu-west-1.rds.amazonaws.com"
s3_bucket_name_prefix: "030-s3-ppr-gitlab-storage"
backup_keep_time: "43200"
vpc_range: "10.0.0.0/8"
environment_valeo: "ppr"
gitlab_db_name: "DUL9PPGT1"
gitlab_version: "-14.10.5"
gitlab_root_password: "{{ lookup('amazon.aws.aws_secret', 'gitlab-ppr-root-user', region='eu-west-1') }}"
gitlab_aws_rds_password: "{{ lookup('amazon.aws.aws_secret', 'gitlab-rds-postgres-db-password-ppr-dul9-sv03091', region='eu-west-1') }}"
ldap_password: "{{ lookup('amazon.aws.aws_secret', '/gitlab/ppr/ldap_password', region='eu-west-1') }}"
ldap_bind_dn: "CN=s-corp-gitlab-ldap-dev,OU=Services Account,OU=Corporate Solution Center,OU=Users and Groups,OU=Service Admin,DC=vnet,DC=valeo,DC=com"
ldap_port: "636"