plugin: aws_ec2

regions:
    - eu-west-1
hostnames:
    - instance-id
filters:
    tag:gitlab_node_type: '*'
    tag:Environment: 'PPR'
keyed_groups:
  - prefix: gitlab_node_type
    key: tags['gitlab_node_type']